### ISSUE TITLE
Checkpoints

### ISSUE THREAD

**Issue by JustAnOkapi** [isamu-isozaki/diffusers#2]
If its not already implemented ive seen autosaving checkpoints and the ability to resume from them in forks like: https://github.com/nicolai256/Stable-textual-inversion_win

**Comment by isamu-isozaki** [comment]
@JustAnOkapi Sounds good! Currently it's saving at every save_interval argument but it overwrites the previous save so I'll try checking that one out too

**Comment by JustAnOkapi** [comment]
can you resume from the save?

**Comment by isamu-isozaki** [comment]
Yup! Should be possible by setting pretrained_model_name_or_path argument. I'll double check if it works today

**Comment by JustAnOkapi** [comment]
Did the checkpoint work?

**Comment by isamu-isozaki** [comment]
Yup! Ill put the code here in the morning but it worked.
