### ISSUE TITLE
accelerate config

### ISSUE THREAD

**Issue by JustAnOkapi** [isamu-isozaki/diffusers#3]
What is the recommended accelerate config for a 1660 6gb
the card doesn't support half precision
when I set up it doesn't use the gpu at all

**Comment by isamu-isozaki** [comment]
I should write this in the readme too but I recommend no mixed precision and just use cpu. The code already puts the unet in gpu so if you enable gpu and put the other stuff in gpu then you'll prob go out of memory

**Comment by isamu-isozaki** [comment]
For deepspeed, I wasn't able to test on my machine but lemme know if you try it out!

**Comment by JustAnOkapi** [comment]
My gpu isnt being used for anything at all.
its 0% with 0/6gb used.

**Comment by isamu-isozaki** [comment]
Interesting. In my code, the only time that happens is when
```
torch.cuda.is_available()
```
is false. Can you run python and see if this is the case?

**Comment by isamu-isozaki** [comment]
also I changed random_crop to data_aug cause I wanted to do some more data augmentation

**Comment by JustAnOkapi** [comment]
i had to reinstall torch with the correct cuda version
`pip3 install torch --extra-index-url https://download.pytorch.org/whl/cu113`
this finally made `torch.cuda.is_available() == True`

**Comment by JustAnOkapi** [comment]
I am running out of vram now
it is using more than 5.8gb even with cpu only enabled

**Comment by isamu-isozaki** [comment]
@JustAnOkapi Awesome. Can you show me your command?

**Comment by isamu-isozaki** [comment]
One option is to put everything in fp16 and set adam's epsilon to 1e-4

**Comment by isamu-isozaki** [comment]
But it should work with 6gb since I was able to run it in mine. My guess is that you might have other processes using your gpu which you can check with nvidia-smi

**Comment by JustAnOkapi** [comment]
`accelerate launch --num_cpu_threads_per_process=6 textual_inversion.py --use_auth_token --pretrained_model_name_or_path="CompVis/stable-diffusion-v1-4" --train_data_dir="brian" --learnable_property="object" --placeholder_token="<brian>" --initializer_token="guy" --resolution=512 --train_batch_size=1 --gradient_accumulation_steps=4 --max_train_steps=3000 --learning_rate=5.0e-04 --scale_lr --lr_scheduler="constant" --lr_warmup_steps=0 --output_dir="textual_inversion_brian" --save_frequency=10`
I am using 0.1/6gb before running and it peaks at 5.8gb trying to allocate 512.

**Comment by JustAnOkapi** [comment]
> thing in fp16 and set adam's epsilo

I cant use fp16 as im on a 16xx card

**Comment by JustAnOkapi** [comment]
I tested other torch and cuda version with no success.

**Comment by isamu-isozaki** [comment]
Ah, I see try setting resolution to 256

**Comment by isamu-isozaki** [comment]
I wasn't able to train it in 512

**Comment by JustAnOkapi** [comment]
![image](https://user-images.githubusercontent.com/39418801/192941763-48d6d1a3-e1b3-4bc6-84ea-f863b088becd.png)
```
ftfy or spacy is not installed using BERT BasicTokenizer instead of ftfy.
The placeholder tokens are <brian>_0 while the ids are [49408]
***** Running training *****
  Num examples = 400
  Num Epochs = 30
  Instantaneous batch size per device = 1
  Total train batch size (w. parallel, distributed & accumulation) = 4
  Gradient Accumulation steps = 4
  Total optimization steps = 3000
Steps:   0%|                                                                                  | 0/3000 [00:00<?, ?it/s]Traceback (most recent call last):
  File "C:\Users\Okapi\Documents\GitHub\diffusers\examples\textual_inversion\textual_inversion.py", line 822, in <module>
    main()
  File "C:\Users\Okapi\Documents\GitHub\diffusers\examples\textual_inversion\textual_inversion.py", line 737, in main
    noise_pred = unet(noisy_latents, timesteps, encoder_hidden_states).sample.to("cpu")
  File "C:\Users\Okapi\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\Okapi\Documents\GitHub\diffusers\src\diffusers\models\unet_2d_condition.py", line 253, in forward
    sample = upsample_block(
  File "C:\Users\Okapi\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\Okapi\Documents\GitHub\diffusers\src\diffusers\models\unet_blocks.py", line 1098, in forward
    hidden_states = attn(hidden_states, context=encoder_hidden_states)
  File "C:\Users\Okapi\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\Okapi\Documents\GitHub\diffusers\src\diffusers\models\attention.py", line 149, in forward
    hidden_states = block(hidden_states, context=context)
  File "C:\Users\Okapi\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\Okapi\Documents\GitHub\diffusers\src\diffusers\models\attention.py", line 198, in forward
    hidden_states = self.attn1(self.norm1(hidden_states)) + hidden_states
  File "C:\Users\Okapi\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\Okapi\Documents\GitHub\diffusers\src\diffusers\models\attention.py", line 268, in forward
    hidden_states = self._attention(query, key, value)
  File "C:\Users\Okapi\Documents\GitHub\diffusers\src\diffusers\models\attention.py", line 275, in _attention
    attention_scores = torch.matmul(query, key.transpose(-1, -2)) * self.scale
RuntimeError: CUDA out of memory. Tried to allocate 512.00 MiB (GPU 0; 6.00 GiB total capacity; 4.89 GiB already allocated; 0 bytes free; 4.92 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

subprocess.CalledProcessError: Command '['C:\\Users\\Okapi\\AppData\\Local\\Programs\\Python\\Python310\\python.exe', 'textual_inversion.py', '--use_auth_token', '--pretrained_model_name_or_path=CompVis/stable-diffusion-v1-4', '--train_data_dir=brian', '--learnable_property=object', '--placeholder_token=<brian>', '--initializer_token=guy', '--resolution=512', '--train_batch_size=1', '--gradient_accumulation_steps=4', '--max_train_steps=3000', '--learning_rate=5.0e-04', '--scale_lr', '--lr_scheduler=constant', '--lr_warmup_steps=0', '--output_dir=textual_inversion_brian', '--save_frequency=10']' returned non-zero exit status 1.
→ ~\Documents\GitHub\diffusers\examples\textual_inversion [6gb ≡ +3 ~1 -0 !]› nvidia-smi
Wed Sep 28 23:50:15 2022
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 517.48       Driver Version: 517.48       CUDA Version: 11.7     |
|-------------------------------+----------------------+----------------------+
| GPU  Name            TCC/WDDM | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ... WDDM  | 00000000:01:00.0  On |                  N/A |
| 38%   38C    P8    10W / 120W |    124MiB /  6144MiB |      4%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A      1372    C+G   C:\WINDOWS\System32\dwm.exe     N/A      |
|    0   N/A  N/A      4552    C+G   ...kyb3d8bbwe\Calculator.exe    N/A      |
|    0   N/A  N/A      5828    C+G   ...lPanel\SystemSettings.exe    N/A      |
|    0   N/A  N/A      6840    C+G   ...5n1h2txyewy\SearchApp.exe    N/A      |
|    0   N/A  N/A     13708    C+G   ...perience\NVIDIA Share.exe    N/A      |
|    0   N/A  N/A     16964    C+G   ...2txyewy\TextInputHost.exe    N/A      |
+-----------------------------------------------------------------------------+
```

**Comment by isamu-isozaki** [comment]
I see. Is that with resolution 256?

**Comment by isamu-isozaki** [comment]
low resolution training on this repo is kinda wonky but it should train. I'm currently comparing with the original https://github.com/isamu-isozaki/fewshot-textual-inversion-low-memory model and see which's better

**Comment by JustAnOkapi** [comment]
> Ah, I see try setting resolution to 256

Lowering res down to 320 allowed it to run,
how badly will this impact the result?

**Comment by isamu-isozaki** [comment]
I never tested with 320 but, in my case, in this model the best dog pic I got was

![a3d989a9-ae26-474e-933f-161f0aadba62](https://user-images.githubusercontent.com/23430101/192943672-25816dcd-acce-429b-8572-f2854162a42d.png)

but I am still experimenting tbh. The main issue is that since this model uses an auto encoder it has edge artifacts. For the glide model, it has more realistic images but it doesn't output the subject as consistently. I'm still testing/developing with parameters but my best recommendation is to try 

train_batch_size=4 with resolution 256 and checkout num_vec_per_token and make the initial token of brian more descriptive than a guy like by including race etc.

**Comment by isamu-isozaki** [comment]
Also I'm improving the other model too so will keep you updated on which is better

**Comment by isamu-isozaki** [comment]
You can check my wandb runs [here](https://wandb.ai/isamu/huggingface_textual_inv?workspace=user-isamu) if you want

**Comment by JustAnOkapi** [comment]
```ftfy or spacy is not installed using BERT BasicTokenizer instead of ftfy.
The placeholder tokens are <brian>_0 while the ids are [49408]
***** Running training *****
  Num examples = 400
  Num Epochs = 30
  Instantaneous batch size per device = 1
  Total train batch size (w. parallel, distributed & accumulation) = 4
  Gradient Accumulation steps = 4
  Total optimization steps = 3000
Steps:   3%|██▊                                                                                 | 100/3000 [18:08<8:41:06, 10.78s/it, loss=0.0441, lr=0.002]Traceback (most recent call last):
  File "C:\Users\Okapi\Documents\GitHub\diffusers\examples\textual_inversion\textual_inversion.py", line 822, in <module>
    main()
  File "C:\Users\Okapi\Documents\GitHub\diffusers\examples\textual_inversion\textual_inversion.py", line 779, in main
    pipeline = get_pipeline(text_encoder, vae, unet, tokenizer, accelerator)
  File "C:\Users\Okapi\Documents\GitHub\diffusers\examples\textual_inversion\textual_inversion.py", line 72, in get_pipeline
    pipeline = StableDiffusionPipelineMixedDevices(
NameError: name 'StableDiffusionPipelineMixedDevices' is not defined```

**Comment by JustAnOkapi** [comment]
> Also I'm improving the other model too so will keep you updated on which is better

Does the glide one still work in stable diffusion?

**Comment by isamu-isozaki** [comment]
Ah for that try uninstalling diffusers then doing

pip install -e . 

At the root of the repo. And nope the glide model isn't pary of the stable diffusion/diffusers but it is pretty similar to imagen which performs better anyway

**Comment by isamu-isozaki** [comment]
Im gonna sleep for now but good luck with making it work!

**Comment by isamu-isozaki** [comment]
@JustAnOkapi Ok I'm getting somewhere. If you see the patches in the output that I showed above, it's mainly from the learning rate being too high/the model not being able to get to the output from the current init token. I'm experimenting with lowering lr+adding in ideas from google's dreambooth. And btw, if you use the dreambooth colab, you can accompish this pretty nicely too.

**Comment by isamu-isozaki** [comment]
@JustAnOkapi Was able to run entire model on gpu now at 512 resolution! Training time is now like 4 hours or so too. Let me know if you have any qs and then I'll probably close this issue
